# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Starting Azure build...
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    python --version
    python3.7 --version
    python -m pip install --upgrade pip pipenv
    python -m pipenv install --dev
    python -m pipenv run lint
  displayName: 'Install pipenv and dependencies and run lint'

